# Generated by Django 5.0.3 on 2024-03-14 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
                ('allergies', models.TextField()),
                ('medical_conditions', models.TextField()),
                ('medications', models.TextField()),
                ('surgical_history', models.TextField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('body_temperature', models.FloatField()),
                ('appointment_date_time', models.DateTimeField()),
                ('visit_history', models.TextField()),
                ('procedures_tests', models.TextField()),
                ('insurance_provider', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=50)),
                ('coverage_details', models.TextField()),
                ('invoicing_details', models.TextField()),
                ('payment_history', models.TextField()),
                ('lab_test_results', models.TextField()),
                ('imaging_reports', models.TextField()),
                ('prescribed_medications', models.TextField(null=True)),
                ('treatment_procedures', models.TextField(null=True)),
                ('specialist_referrals', models.TextField(null=True)),
                ('physician_notes', models.TextField(null=True)),
                ('nurse_observations', models.TextField(null=True)),
                ('progress_notes', models.TextField(null=True)),
                ('emergency_contact_name', models.CharField(max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(max_length=20, null=True)),
                ('treatment_consent', models.BooleanField(default=True)),
                ('data_sharing_consent', models.BooleanField(default=True)),
                ('communication_logs', models.TextField()),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hospital')),
            ],
        ),
    ]
