# Generated by Django 5.0.3 on 2024-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment_date_time',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='body_temperature',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='communication_logs',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coverage_details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='data_sharing_consent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='imaging_reports',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='invoicing_details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lab_test_results',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nurse_observations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='payment_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='physician_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prescribed_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='procedures_tests',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='progress_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='specialist_referrals',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_consent',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_procedures',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
